export enum Tipo {
  CATEGORIA_SERVICIO = 'TIPO_SERVICIO',
  CATEGORIA_PUBLICACION = 'TIPO_PUBLICACION',
  TIPO_TRABAJO = 'TIPO_TRABAJO',
  GENERAL = 'GENERAL',
  TIPO_DOCUMENTO = 'TIPO_DOCUMENTO',
  TIPO_CLIENTE = 'TIPO_CLIENTE',
}
